import { ReportDefinition } from '../../types/reports.types';

export const reportDefinitionsRegistry: ReportDefinition[] = [
  // ==========================================================================
  // MASTER TRANSACTION REPORT
  // ==========================================================================
  {
    id: 'raw_transactions',
    name: 'Raw Sales Transactions Report',
    description: 'Master itemized log of every sale transaction with invoice, customer, product, costing, profit, and payment details',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: [
      'invoice_id', 'invoice_number', 'invoice_date', 'invoice_time', 'completed_at',
      'customer_id', 'customer_name', 'customer_code', 'customer_phone', 'customer_category',
      'product_id', 'product_name', 'sku', 'variant_name', 'category', 'subcategory', 'unit_type',
      'payment_method', 'upi_reference', 'cashier_name', 'cashier_id', 'shift_id', 'counter_id',
      'location_name', 'location_id', 'transaction_status', 'payment_status'
    ],
    availableMeasures: [
      'quantity', 'weight_kg', 'selling_price_paise', 'gross_amount_paise', 'discount_paise',
      'taxable_amount_paise', 'tax_paise', 'net_amount_paise', 'cost_paise', 'gross_profit_paise',
      'margin_percent', 'payment_amount_paise'
    ],
    defaultColumns: [
      { id: 'invoice_number', label: 'Invoice #', visible: true, width: 130, pinned: true },
      { id: 'invoice_date', label: 'Date', visible: true, width: 105 },
      { id: 'invoice_time', label: 'Time', visible: true, width: 85 },
      { id: 'customer_name', label: 'Customer', visible: true, width: 160 },
      { id: 'customer_phone', label: 'Phone', visible: true, width: 110 },
      { id: 'product_name', label: 'Product', visible: true, width: 150 },
      { id: 'variant_name', label: 'Variant', visible: true, width: 110 },
      { id: 'category', label: 'Category', visible: true, width: 110 },
      { id: 'quantity', label: 'Qty', visible: true, width: 70 },
      { id: 'weight_kg', label: 'Weight (kg)', visible: true, width: 100 },
      { id: 'selling_price_paise', label: 'Rate (₹)', visible: true, width: 95 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 105 },
      { id: 'discount_paise', label: 'Discount (₹)', visible: true, width: 95 },
      { id: 'taxable_amount_paise', label: 'Taxable (₹)', visible: false, width: 105 },
      { id: 'tax_paise', label: 'Tax (₹)', visible: true, width: 90 },
      { id: 'net_amount_paise', label: 'Net (₹)', visible: true, width: 110 },
      { id: 'cost_paise', label: 'Cost (₹)', visible: true, width: 95 },
      { id: 'gross_profit_paise', label: 'Profit (₹)', visible: true, width: 100 },
      { id: 'margin_percent', label: 'Margin %', visible: true, width: 90 },
      { id: 'payment_method', label: 'Payment', visible: true, width: 95 },
      { id: 'cashier_name', label: 'Cashier', visible: true, width: 100 },
    ],
    defaultSortBy: [{ field: 'completed_at', direction: 'desc' }],
    pageSize: 50,
  },

  // ==========================================================================
  // SECTION A: SALES REPORTS
  // ==========================================================================
  {
    id: 'sales_by_date',
    name: 'Sales by Date',
    description: 'Timeline sales aggregation across days, weeks, months, or years',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['invoice_date', 'month_year', 'day_of_week'],
    availableMeasures: [
      'invoice_count', 'quantity', 'weight_kg', 'gross_amount_paise', 'discount_paise',
      'tax_paise', 'net_amount_paise', 'cost_paise', 'gross_profit_paise', 'margin_percent', 'avg_basket_value_paise'
    ],
    defaultColumns: [
      { id: 'invoice_date', label: 'Date', visible: true, width: 120, pinned: true },
      { id: 'invoice_count', label: 'Invoices', visible: true, width: 90 },
      { id: 'weight_kg', label: 'Total Weight (kg)', visible: true, width: 130 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 120 },
      { id: 'discount_paise', label: 'Discount (₹)', visible: true, width: 105 },
      { id: 'tax_paise', label: 'Tax (₹)', visible: true, width: 100 },
      { id: 'net_amount_paise', label: 'Net Sales (₹)', visible: true, width: 130 },
      { id: 'cost_paise', label: 'Cost (₹)', visible: true, width: 110 },
      { id: 'gross_profit_paise', label: 'Gross Profit (₹)', visible: true, width: 130 },
      { id: 'margin_percent', label: 'Margin %', visible: true, width: 95 },
      { id: 'avg_basket_value_paise', label: 'Avg Ticket (₹)', visible: true, width: 115 },
    ],
    defaultGroupBy: ['invoice_date'],
    defaultSortBy: [{ field: 'invoice_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_product',
    name: 'Sales by Product',
    description: 'Product volume, revenue, costing, margins, unit metrics, and return volumes',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['product_name', 'variant_name', 'sku', 'category', 'unit_type'],
    availableMeasures: [
      'quantity', 'weight_kg', 'gross_amount_paise', 'discount_paise', 'net_amount_paise',
      'cost_paise', 'gross_profit_paise', 'margin_percent', 'invoice_count', 'selling_price_paise'
    ],
    defaultColumns: [
      { id: 'product_name', label: 'Product', visible: true, width: 180, pinned: true },
      { id: 'category', label: 'Category', visible: true, width: 120 },
      { id: 'unit_type', label: 'Unit', visible: true, width: 90 },
      { id: 'invoice_count', label: 'Invoices', visible: true, width: 90 },
      { id: 'quantity', label: 'Qty Units', visible: true, width: 95 },
      { id: 'weight_kg', label: 'Weight (kg)', visible: true, width: 120 },
      { id: 'selling_price_paise', label: 'Avg Rate (₹)', visible: true, width: 110 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 120 },
      { id: 'discount_paise', label: 'Discount (₹)', visible: true, width: 105 },
      { id: 'net_amount_paise', label: 'Net Revenue (₹)', visible: true, width: 130 },
      { id: 'cost_paise', label: 'Total Cost (₹)', visible: true, width: 115 },
      { id: 'gross_profit_paise', label: 'Gross Profit (₹)', visible: true, width: 130 },
      { id: 'margin_percent', label: 'Margin %', visible: true, width: 95 },
    ],
    defaultGroupBy: ['product_name'],
    defaultSortBy: [{ field: 'net_amount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_category',
    name: 'Sales by Category',
    description: 'Category and subcategory sales summary with margin analytics and drill-down into products',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['category', 'subcategory'],
    availableMeasures: [
      'item_count', 'invoice_count', 'quantity', 'weight_kg', 'gross_amount_paise',
      'discount_paise', 'tax_paise', 'net_amount_paise', 'cost_paise', 'gross_profit_paise', 'margin_percent'
    ],
    defaultColumns: [
      { id: 'category', label: 'Category', visible: true, width: 180, pinned: true },
      { id: 'invoice_count', label: 'Invoices', visible: true, width: 100 },
      { id: 'item_count', label: 'Items Sold', visible: true, width: 100 },
      { id: 'weight_kg', label: 'Total Weight (kg)', visible: true, width: 135 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 125 },
      { id: 'discount_paise', label: 'Discount (₹)', visible: true, width: 110 },
      { id: 'tax_paise', label: 'Tax (₹)', visible: true, width: 100 },
      { id: 'net_amount_paise', label: 'Net Revenue (₹)', visible: true, width: 140 },
      { id: 'cost_paise', label: 'Cost (₹)', visible: true, width: 115 },
      { id: 'gross_profit_paise', label: 'Profit (₹)', visible: true, width: 130 },
      { id: 'margin_percent', label: 'Margin %', visible: true, width: 100 },
    ],
    defaultGroupBy: ['category'],
    defaultSortBy: [{ field: 'net_amount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_customer',
    name: 'Sales by Customer',
    description: 'Individual customer sales, transaction frequency, volume, and profitability',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['customer_name', 'customer_code', 'customer_phone', 'customer_category'],
    availableMeasures: [
      'invoice_count', 'weight_kg', 'quantity', 'gross_amount_paise', 'discount_paise',
      'net_amount_paise', 'cost_paise', 'gross_profit_paise', 'margin_percent', 'avg_basket_value_paise'
    ],
    defaultColumns: [
      { id: 'customer_name', label: 'Customer', visible: true, width: 180, pinned: true },
      { id: 'customer_phone', label: 'Phone', visible: true, width: 120 },
      { id: 'customer_category', label: 'Type', visible: true, width: 105 },
      { id: 'invoice_count', label: 'Orders', visible: true, width: 90 },
      { id: 'weight_kg', label: 'Weight (kg)', visible: true, width: 115 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 115 },
      { id: 'discount_paise', label: 'Discount (₹)', visible: true, width: 105 },
      { id: 'net_amount_paise', label: 'Net Spend (₹)', visible: true, width: 130 },
      { id: 'gross_profit_paise', label: 'Profit (₹)', visible: true, width: 120 },
      { id: 'margin_percent', label: 'Margin %', visible: true, width: 95 },
      { id: 'avg_basket_value_paise', label: 'Avg Ticket (₹)', visible: true, width: 115 },
    ],
    defaultGroupBy: ['customer_name'],
    defaultSortBy: [{ field: 'net_amount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_customer_group',
    name: 'Sales by Customer Group',
    description: 'Sales performance segmented by customer tiers (Retail, Wholesale, VIP, Hotel/Restaurant)',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['customer_category'],
    availableMeasures: [
      'invoice_count', 'weight_kg', 'gross_amount_paise', 'discount_paise',
      'net_amount_paise', 'cost_paise', 'gross_profit_paise', 'margin_percent', 'avg_basket_value_paise'
    ],
    defaultColumns: [
      { id: 'customer_category', label: 'Customer Group', visible: true, width: 160, pinned: true },
      { id: 'invoice_count', label: 'Invoices', visible: true, width: 100 },
      { id: 'weight_kg', label: 'Total Weight (kg)', visible: true, width: 130 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 120 },
      { id: 'discount_paise', label: 'Discount (₹)', visible: true, width: 110 },
      { id: 'net_amount_paise', label: 'Net Sales (₹)', visible: true, width: 135 },
      { id: 'gross_profit_paise', label: 'Gross Profit (₹)', visible: true, width: 130 },
      { id: 'margin_percent', label: 'Margin %', visible: true, width: 100 },
      { id: 'avg_basket_value_paise', label: 'Avg Order Value (₹)', visible: true, width: 135 },
    ],
    defaultGroupBy: ['customer_category'],
    defaultSortBy: [{ field: 'net_amount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_cashier',
    name: 'Sales by Cashier',
    description: 'Cashier sales performance, ticket counts, discount volume, and payment collection split',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['cashier_name', 'cashier_id'],
    availableMeasures: [
      'invoice_count', 'weight_kg', 'gross_amount_paise', 'discount_paise', 'net_amount_paise',
      'cash_collected_paise', 'digital_collected_paise', 'avg_basket_value_paise'
    ],
    defaultColumns: [
      { id: 'cashier_name', label: 'Cashier / User', visible: true, width: 160, pinned: true },
      { id: 'invoice_count', label: 'Invoices Billed', visible: true, width: 115 },
      { id: 'weight_kg', label: 'Weight Sold (kg)', visible: true, width: 130 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 120 },
      { id: 'discount_paise', label: 'Discounts Given (₹)', visible: true, width: 135 },
      { id: 'net_amount_paise', label: 'Net Collected (₹)', visible: true, width: 135 },
      { id: 'cash_collected_paise', label: 'Cash (₹)', visible: true, width: 110 },
      { id: 'digital_collected_paise', label: 'Digital/UPI (₹)', visible: true, width: 125 },
      { id: 'avg_basket_value_paise', label: 'Avg Ticket (₹)', visible: true, width: 120 },
    ],
    defaultGroupBy: ['cashier_name'],
    defaultSortBy: [{ field: 'net_amount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_shift',
    name: 'Sales by Shift',
    description: 'Sales and collection figures broken down by operational shift',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['shift_id', 'counter_id', 'invoice_date'],
    availableMeasures: [
      'invoice_count', 'weight_kg', 'net_amount_paise', 'cash_collected_paise',
      'upi_collected_paise', 'card_collected_paise', 'avg_basket_value_paise'
    ],
    defaultColumns: [
      { id: 'shift_id', label: 'Shift #', visible: true, width: 100, pinned: true },
      { id: 'counter_id', label: 'Counter', visible: true, width: 110 },
      { id: 'invoice_count', label: 'Invoices', visible: true, width: 95 },
      { id: 'weight_kg', label: 'Weight (kg)', visible: true, width: 120 },
      { id: 'cash_collected_paise', label: 'Cash (₹)', visible: true, width: 115 },
      { id: 'upi_collected_paise', label: 'UPI (₹)', visible: true, width: 115 },
      { id: 'card_collected_paise', label: 'Card (₹)', visible: true, width: 110 },
      { id: 'net_amount_paise', label: 'Total Revenue (₹)', visible: true, width: 135 },
    ],
    defaultGroupBy: ['shift_id'],
    defaultSortBy: [{ field: 'shift_id', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_payment_method',
    name: 'Sales by Payment Method',
    description: 'Breakdown of transactions and revenue by payment method (Cash, UPI, Card, Credit)',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['payment_method'],
    availableMeasures: [
      'invoice_count', 'item_count', 'gross_amount_paise', 'discount_paise',
      'tax_paise', 'net_amount_paise', 'payment_amount_paise'
    ],
    defaultColumns: [
      { id: 'payment_method', label: 'Payment Method', visible: true, width: 150, pinned: true },
      { id: 'invoice_count', label: 'Invoices', visible: true, width: 100 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 120 },
      { id: 'discount_paise', label: 'Discount (₹)', visible: true, width: 110 },
      { id: 'tax_paise', label: 'Tax (₹)', visible: true, width: 100 },
      { id: 'net_amount_paise', label: 'Net Collected (₹)', visible: true, width: 140 },
    ],
    defaultGroupBy: ['payment_method'],
    defaultSortBy: [{ field: 'net_amount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_day_of_week',
    name: 'Sales by Day of Week',
    description: 'Weekly sales patterns to identify peak meat shopping days (e.g. Sunday surges)',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['day_of_week'],
    availableMeasures: [
      'invoice_count', 'weight_kg', 'gross_amount_paise', 'discount_paise',
      'net_amount_paise', 'gross_profit_paise', 'margin_percent', 'avg_basket_value_paise'
    ],
    defaultColumns: [
      { id: 'day_of_week', label: 'Day of Week', visible: true, width: 150, pinned: true },
      { id: 'invoice_count', label: 'Invoices', visible: true, width: 100 },
      { id: 'weight_kg', label: 'Total Weight (kg)', visible: true, width: 135 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 120 },
      { id: 'net_amount_paise', label: 'Net Revenue (₹)', visible: true, width: 135 },
      { id: 'gross_profit_paise', label: 'Gross Profit (₹)', visible: true, width: 130 },
      { id: 'margin_percent', label: 'Margin %', visible: true, width: 100 },
      { id: 'avg_basket_value_paise', label: 'Avg Ticket (₹)', visible: true, width: 125 },
    ],
    defaultGroupBy: ['day_of_week'],
    defaultSortBy: [{ field: 'net_amount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_hour',
    name: 'Sales by Hour of Day',
    description: 'Hourly sales distribution to analyze peak counter congestion and morning/evening rushes',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['hour_of_day'],
    availableMeasures: [
      'invoice_count', 'weight_kg', 'net_amount_paise', 'gross_profit_paise', 'avg_basket_value_paise'
    ],
    defaultColumns: [
      { id: 'hour_of_day', label: 'Hour of Day', visible: true, width: 130, pinned: true },
      { id: 'invoice_count', label: 'Invoices', visible: true, width: 100 },
      { id: 'weight_kg', label: 'Weight Sold (kg)', visible: true, width: 135 },
      { id: 'net_amount_paise', label: 'Net Revenue (₹)', visible: true, width: 140 },
      { id: 'gross_profit_paise', label: 'Gross Profit (₹)', visible: true, width: 130 },
      { id: 'avg_basket_value_paise', label: 'Avg Ticket (₹)', visible: true, width: 125 },
    ],
    defaultGroupBy: ['hour_of_day'],
    defaultSortBy: [{ field: 'hour_of_day', direction: 'asc' }],
    pageSize: 50,
  },

  {
    id: 'sales_by_location',
    name: 'Sales by Location / Branch',
    description: 'Store and branch comparison for multi-outlet retail setups',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['location_name', 'location_id'],
    availableMeasures: [
      'invoice_count', 'weight_kg', 'net_amount_paise', 'cost_paise', 'gross_profit_paise', 'margin_percent'
    ],
    defaultColumns: [
      { id: 'location_name', label: 'Branch / Location', visible: true, width: 170, pinned: true },
      { id: 'invoice_count', label: 'Total Invoices', visible: true, width: 110 },
      { id: 'weight_kg', label: 'Weight (kg)', visible: true, width: 125 },
      { id: 'net_amount_paise', label: 'Net Revenue (₹)', visible: true, width: 135 },
      { id: 'cost_paise', label: 'Total Cost (₹)', visible: true, width: 120 },
      { id: 'gross_profit_paise', label: 'Gross Profit (₹)', visible: true, width: 130 },
      { id: 'margin_percent', label: 'Margin %', visible: true, width: 100 },
    ],
    defaultGroupBy: ['location_name'],
    defaultSortBy: [{ field: 'net_amount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'returns_and_refunds',
    name: 'Returns & Refunds Report',
    description: 'Detailed customer returns, reasons, refund channels, and return rate analytics',
    dataSource: 'sales_returns',
    category: 'Sales Reports',
    availableDimensions: [
      'return_number', 'invoice_number', 'return_date', 'customer_name',
      'product_name', 'variant_name', 'reason', 'refund_method', 'cashier_name'
    ],
    availableMeasures: ['quantity', 'weight_kg', 'unit_rate_paise', 'refund_amount_paise', 'return_count'],
    defaultColumns: [
      { id: 'return_number', label: 'Return #', visible: true, width: 130, pinned: true },
      { id: 'invoice_number', label: 'Original Invoice #', visible: true, width: 130 },
      { id: 'return_date', label: 'Return Date', visible: true, width: 105 },
      { id: 'customer_name', label: 'Customer', visible: true, width: 150 },
      { id: 'product_name', label: 'Product', visible: true, width: 150 },
      { id: 'weight_kg', label: 'Weight (kg)', visible: true, width: 105 },
      { id: 'unit_rate_paise', label: 'Rate (₹)', visible: true, width: 95 },
      { id: 'refund_amount_paise', label: 'Refund Amount (₹)', visible: true, width: 130 },
      { id: 'reason', label: 'Reason', visible: true, width: 150 },
      { id: 'refund_method', label: 'Refund Method', visible: true, width: 120 },
      { id: 'cashier_name', label: 'Processed By', visible: true, width: 110 },
    ],
    defaultSortBy: [{ field: 'return_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'discounts_report',
    name: 'Discounts & Concessions Report',
    description: 'Discount analysis across invoices, cashiers, customers, and discount abuse audit',
    dataSource: 'sales_transactions',
    category: 'Sales Reports',
    availableDimensions: ['invoice_number', 'invoice_date', 'customer_name', 'cashier_name', 'discount_reason'],
    availableMeasures: ['discount_paise', 'discount_percent', 'gross_amount_paise', 'net_amount_paise'],
    defaultColumns: [
      { id: 'invoice_number', label: 'Invoice #', visible: true, width: 130, pinned: true },
      { id: 'invoice_date', label: 'Date', visible: true, width: 105 },
      { id: 'customer_name', label: 'Customer', visible: true, width: 150 },
      { id: 'cashier_name', label: 'Cashier', visible: true, width: 110 },
      { id: 'discount_reason', label: 'Reason', visible: true, width: 140 },
      { id: 'gross_amount_paise', label: 'Gross (₹)', visible: true, width: 110 },
      { id: 'discount_paise', label: 'Discount (₹)', visible: true, width: 120 },
      { id: 'discount_percent', label: 'Discount %', visible: true, width: 100 },
      { id: 'net_amount_paise', label: 'Net Billed (₹)', visible: true, width: 120 },
    ],
    defaultSortBy: [{ field: 'discount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  // ==========================================================================
  // SECTION B: PROFITABILITY & COGS REPORTS
  // ==========================================================================
  {
    id: 'product_profitability',
    name: 'Product Profitability Report',
    description: 'Comprehensive product profitability with meat-shop specific metrics: Cost/kg, Selling Price/kg, and Profit/kg',
    dataSource: 'sales_transactions',
    category: 'Profitability & COGS',
    availableDimensions: ['product_name', 'variant_name', 'category', 'unit_type'],
    availableMeasures: [
      'weight_kg', 'quantity', 'gross_amount_paise', 'discount_paise', 'net_amount_paise',
      'cost_paise', 'gross_profit_paise', 'margin_percent', 'cost_per_kg_paise',
      'selling_price_per_kg_paise', 'profit_per_kg_paise'
    ],
    defaultColumns: [
      { id: 'product_name', label: 'Product', visible: true, width: 180, pinned: true },
      { id: 'category', label: 'Category', visible: true, width: 120 },
      { id: 'weight_kg', label: 'Weight Sold (kg)', visible: true, width: 125 },
      { id: 'cost_per_kg_paise', label: 'Cost/kg (₹)', visible: true, width: 115 },
      { id: 'selling_price_per_kg_paise', label: 'Selling Price/kg (₹)', visible: true, width: 135 },
      { id: 'profit_per_kg_paise', label: 'Profit/kg (₹)', visible: true, width: 120 },
      { id: 'net_amount_paise', label: 'Net Revenue (₹)', visible: true, width: 130 },
      { id: 'cost_paise', label: 'Total COGS (₹)', visible: true, width: 120 },
      { id: 'gross_profit_paise', label: 'Gross Profit (₹)', visible: true, width: 130 },
      { id: 'margin_percent', label: 'Gross Margin %', visible: true, width: 115 },
    ],
    defaultGroupBy: ['product_name'],
    defaultSortBy: [{ field: 'gross_profit_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'cogs_report',
    name: 'COGS & Inventory Valuation',
    description: 'Inventory valuation, stock holding values, and explicit costing methods (Actual WAC vs Estimated vs Missing)',
    dataSource: 'cogs_inventory',
    category: 'Profitability & COGS',
    availableDimensions: ['product_name', 'variant_name', 'sku', 'category', 'unit_type', 'costing_method'],
    availableMeasures: [
      'cost_price_paise_per_unit', 'last_purchase_cost_paise', 'weighted_average_cost_paise',
      'selling_price_paise', 'stock_weight_kg', 'stock_valuation_paise'
    ],
    defaultColumns: [
      { id: 'product_name', label: 'Product', visible: true, width: 180, pinned: true },
      { id: 'category', label: 'Category', visible: true, width: 120 },
      { id: 'costing_method', label: 'Costing Method', visible: true, width: 180 },
      { id: 'cost_price_paise_per_unit', label: 'Base Cost (₹)', visible: true, width: 110 },
      { id: 'last_purchase_cost_paise', label: 'Last Purchase (₹)', visible: true, width: 125 },
      { id: 'weighted_average_cost_paise', label: 'WAC (₹)', visible: true, width: 105 },
      { id: 'stock_weight_kg', label: 'Stock on Hand (kg)', visible: true, width: 135 },
      { id: 'stock_valuation_paise', label: 'Stock Value (₹)', visible: true, width: 135 },
    ],
    defaultSortBy: [{ field: 'stock_valuation_paise', direction: 'desc' }],
    pageSize: 50,
  },

  // ==========================================================================
  // SECTION C: PAYMENTS, UPI & RECONCILIATION
  // ==========================================================================
  {
    id: 'payment_summary_report',
    name: 'Payment Summary & Log',
    description: 'Transaction-level payment entries across Cash, UPI, Card, and Credit allocations',
    dataSource: 'payment_records',
    category: 'Payments & Reconciliation',
    availableDimensions: [
      'payment_id', 'invoice_number', 'payment_date', 'payment_time',
      'customer_name', 'customer_phone', 'payment_method', 'reference_number',
      'cashier_name', 'location_name'
    ],
    availableMeasures: ['amount_paise', 'payment_count'],
    defaultColumns: [
      { id: 'invoice_number', label: 'Invoice #', visible: true, width: 130, pinned: true },
      { id: 'payment_date', label: 'Date', visible: true, width: 105 },
      { id: 'payment_time', label: 'Time', visible: true, width: 85 },
      { id: 'customer_name', label: 'Customer', visible: true, width: 150 },
      { id: 'payment_method', label: 'Method', visible: true, width: 100 },
      { id: 'reference_number', label: 'Reference / UTR', visible: true, width: 150 },
      { id: 'amount_paise', label: 'Amount (₹)', visible: true, width: 125 },
      { id: 'cashier_name', label: 'Cashier', visible: true, width: 110 },
      { id: 'location_name', label: 'Branch', visible: true, width: 120 },
    ],
    defaultSortBy: [{ field: 'payment_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'upi_report',
    name: 'UPI Transactions & Reconciliation',
    description: 'UPI transaction tracking, verified VPA customer linking, and gateway reconciliation status',
    dataSource: 'upi_reconciliation',
    category: 'Payments & Reconciliation',
    availableDimensions: [
      'payment_id', 'upi_ref', 'invoice_number', 'transaction_date', 'transaction_time',
      'customer_name', 'customer_phone', 'vpa', 'reconciliation_status', 'cashier_name'
    ],
    availableMeasures: ['amount_paise', 'transaction_count'],
    defaultColumns: [
      { id: 'upi_ref', label: 'UPI Reference / UTR', visible: true, width: 160, pinned: true },
      { id: 'invoice_number', label: 'Invoice #', visible: true, width: 130 },
      { id: 'transaction_date', label: 'Date', visible: true, width: 105 },
      { id: 'customer_name', label: 'Linked Customer', visible: true, width: 160 },
      { id: 'vpa', label: 'Matched VPA', visible: true, width: 160 },
      { id: 'amount_paise', label: 'Amount (₹)', visible: true, width: 120 },
      { id: 'reconciliation_status', label: 'Reconciliation Status', visible: true, width: 170 },
      { id: 'cashier_name', label: 'Cashier', visible: true, width: 110 },
    ],
    defaultSortBy: [{ field: 'transaction_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'payment_reconciliation_report',
    name: 'Payment Reconciliation Report',
    description: 'Compares POS recorded payments against verified payment gateway / bank settlement figures',
    dataSource: 'payment_records',
    category: 'Payments & Reconciliation',
    availableDimensions: ['payment_method', 'payment_date'],
    availableMeasures: ['amount_paise', 'payment_count'],
    defaultColumns: [
      { id: 'payment_method', label: 'Payment Method', visible: true, width: 160, pinned: true },
      { id: 'payment_count', label: 'POS Transactions', visible: true, width: 130 },
      { id: 'amount_paise', label: 'POS Recorded (₹)', visible: true, width: 150 },
    ],
    defaultGroupBy: ['payment_method'],
    defaultSortBy: [{ field: 'amount_paise', direction: 'desc' }],
    pageSize: 50,
  },

  // ============================================================================
  // Section A — Customer Reports (Phase 3)
  // ============================================================================

  {
    id: 'customer_sales_report',
    name: 'Customer Sales Report',
    description: 'Comprehensive customer purchasing volume, visit cadence, favorite items, and payment preferences',
    dataSource: 'customer_sales_intelligence',
    category: 'Customer Reports',
    availableDimensions: [
      'customer_code',
      'customer_name',
      'phone',
      'category',
      'customer_segment',
      'first_visit_date',
      'last_visit_date',
      'expected_next_visit',
      'payment_preference',
      'preferred_visit_day',
      'purchase_frequency_label',
      'favorite_products_summary',
    ],
    availableMeasures: [
      'total_orders',
      'total_revenue_paise',
      'total_weight_kg',
      'avg_bill_paise',
      'avg_visit_interval_days',
      'days_since_last_visit',
      'outstanding_balance_paise',
      'advance_balance_paise',
    ],
    defaultColumns: [
      { id: 'customer_name', label: 'Customer', visible: true, width: 160, pinned: true },
      { id: 'category', label: 'Category', visible: true, width: 110 },
      { id: 'total_orders', label: 'Orders', visible: true, width: 90 },
      { id: 'total_revenue_paise', label: 'Revenue (₹)', visible: true, width: 130 },
      { id: 'total_weight_kg', label: 'Weight (kg)', visible: true, width: 110 },
      { id: 'avg_bill_paise', label: 'Avg Bill (₹)', visible: true, width: 120 },
      { id: 'last_visit_date', label: 'Last Visit', visible: true, width: 110 },
      { id: 'first_visit_date', label: 'First Visit', visible: true, width: 110 },
      { id: 'avg_visit_interval_days', label: 'Visit Interval (d)', visible: true, width: 130 },
      { id: 'favorite_products_summary', label: 'Favorite Products', visible: true, width: 180 },
      { id: 'payment_preference', label: 'Payment Preference', visible: true, width: 140 },
    ],
    defaultSortBy: [{ field: 'total_revenue_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'customer_profitability_report',
    name: 'Customer Profitability Report',
    description: 'Customer-level contribution margin, gross profit, discounts, and profitability metrics',
    dataSource: 'sales_transactions',
    category: 'Customer Reports',
    availableDimensions: ['customer_name', 'customer_category', 'payment_method'],
    availableMeasures: [
      'gross_amount_paise',
      'discount_paise',
      'net_amount_paise',
      'cost_paise',
      'gross_profit_paise',
      'margin_percent',
    ],
    defaultColumns: [
      { id: 'customer_name', label: 'Customer', visible: true, width: 170, pinned: true },
      { id: 'customer_category', label: 'Category', visible: true, width: 120 },
      { id: 'gross_amount_paise', label: 'Gross Sales (₹)', visible: true, width: 130 },
      { id: 'discount_paise', label: 'Discounts (₹)', visible: true, width: 120 },
      { id: 'net_amount_paise', label: 'Net Sales (₹)', visible: true, width: 130 },
      { id: 'cost_paise', label: 'COGS (₹)', visible: true, width: 120 },
      { id: 'gross_profit_paise', label: 'Gross Profit (₹)', visible: true, width: 130 },
      { id: 'margin_percent', label: 'Gross Margin %', visible: true, width: 130 },
    ],
    defaultGroupBy: ['customer_name'],
    defaultSortBy: [{ field: 'gross_profit_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'customer_activity_report',
    name: 'Customer Activity & Visit Cadence',
    description: 'Customer visit recency, expected next visits, visit frequencies, and lapsed days',
    dataSource: 'customer_sales_intelligence',
    category: 'Customer Reports',
    availableDimensions: [
      'customer_name',
      'phone',
      'category',
      'customer_segment',
      'last_visit_date',
      'last_payment_date',
      'expected_next_visit',
      'purchase_frequency_label',
    ],
    availableMeasures: [
      'days_since_last_visit',
      'days_overdue',
      'avg_visit_interval_days',
      'total_orders',
      'total_revenue_paise',
      'outstanding_balance_paise',
    ],
    defaultColumns: [
      { id: 'customer_name', label: 'Customer', visible: true, width: 160, pinned: true },
      { id: 'phone', label: 'Phone', visible: true, width: 120 },
      { id: 'customer_segment', label: 'CRM Segment', visible: true, width: 120 },
      { id: 'last_visit_date', label: 'Last Purchase', visible: true, width: 115 },
      { id: 'last_payment_date', label: 'Last Payment', visible: true, width: 115 },
      { id: 'purchase_frequency_label', label: 'Visit Frequency', visible: true, width: 130 },
      { id: 'avg_visit_interval_days', label: 'Interval (d)', visible: true, width: 110 },
      { id: 'expected_next_visit', label: 'Expected Next Visit', visible: true, width: 140 },
      { id: 'days_overdue', label: 'Days Overdue', visible: true, width: 120 },
    ],
    defaultSortBy: [{ field: 'days_overdue', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'customer_retention_report',
    name: 'Customer Retention & Segmentation Report',
    description: 'Cohort breakdown of VIP, Regular, Due, At Risk, Inactive, and New customers',
    dataSource: 'customer_sales_intelligence',
    category: 'Customer Reports',
    availableDimensions: [
      'customer_segment',
      'customer_name',
      'category',
      'phone',
      'purchase_frequency_label',
    ],
    availableMeasures: [
      'total_orders',
      'total_revenue_paise',
      'days_since_last_visit',
      'clv_paise',
      'customer_count',
    ],
    defaultColumns: [
      { id: 'customer_segment', label: 'Segment', visible: true, width: 130, pinned: true },
      { id: 'customer_name', label: 'Customer', visible: true, width: 160 },
      { id: 'category', label: 'Category', visible: true, width: 110 },
      { id: 'total_orders', label: 'Total Orders', visible: true, width: 110 },
      { id: 'total_revenue_paise', label: 'Total Spend (₹)', visible: true, width: 130 },
      { id: 'days_since_last_visit', label: 'Days Inactive', visible: true, width: 120 },
      { id: 'clv_paise', label: 'LTV (₹)', visible: true, width: 120 },
    ],
    defaultGroupBy: ['customer_segment'],
    defaultSortBy: [{ field: 'total_revenue_paise', direction: 'desc' }],
    pageSize: 50,
  },

  // ============================================================================
  // Section B & C — Credit, A/R & Advances Reports (Phase 3)
  // ============================================================================

  {
    id: 'ar_outstanding_report',
    name: 'Outstanding Invoices Report',
    description: 'Itemized unpaid and partially paid credit invoices with overdue days and live balances',
    dataSource: 'ar_outstanding_invoices',
    category: 'Credit & A/R Reports',
    availableDimensions: [
      'invoice_number',
      'customer_code',
      'customer_name',
      'phone',
      'category',
      'invoice_date',
      'due_date',
      'payment_status',
    ],
    availableMeasures: [
      'original_amount_paise',
      'paid_amount_paise',
      'outstanding_amount_paise',
      'days_overdue',
      'credit_limit_paise',
    ],
    defaultColumns: [
      { id: 'customer_name', label: 'Customer', visible: true, width: 160, pinned: true },
      { id: 'customer_code', label: 'Code', visible: true, width: 100 },
      { id: 'invoice_number', label: 'Invoice #', visible: true, width: 130 },
      { id: 'invoice_date', label: 'Invoice Date', visible: true, width: 110 },
      { id: 'due_date', label: 'Due Date', visible: true, width: 110 },
      { id: 'original_amount_paise', label: 'Original (₹)', visible: true, width: 120 },
      { id: 'paid_amount_paise', label: 'Paid (₹)', visible: true, width: 110 },
      { id: 'outstanding_amount_paise', label: 'Outstanding (₹)', visible: true, width: 130 },
      { id: 'days_overdue', label: 'Days Overdue', visible: true, width: 120 },
      { id: 'credit_limit_paise', label: 'Credit Limit (₹)', visible: true, width: 130 },
    ],
    defaultSortBy: [{ field: 'days_overdue', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'ar_aging_report',
    name: 'Accounts Receivable Aging Schedule',
    description: 'Outstanding balances classified into aging buckets (0–15, 16–30, 31–60, 60+ days) matching Credit & A/R aging',
    dataSource: 'ar_aging_summary',
    category: 'Credit & A/R Reports',
    availableDimensions: ['customer_code', 'customer_name', 'phone', 'category', 'risk_level', 'credit_status'],
    availableMeasures: [
      'current_bucket_paise',
      'bucket_1_paise',
      'bucket_2_paise',
      'bucket_3_paise',
      'total_outstanding_paise',
      'credit_limit_paise',
      'available_credit_paise',
    ],
    defaultColumns: [
      { id: 'customer_name', label: 'Customer', visible: true, width: 160, pinned: true },
      { id: 'customer_code', label: 'Code', visible: true, width: 100 },
      { id: 'current_bucket_paise', label: '0–15 Days (₹)', visible: true, width: 120 },
      { id: 'bucket_1_paise', label: '16–30 Days (₹)', visible: true, width: 120 },
      { id: 'bucket_2_paise', label: '31–60 Days (₹)', visible: true, width: 120 },
      { id: 'bucket_3_paise', label: '60+ Days (₹)', visible: true, width: 120 },
      { id: 'total_outstanding_paise', label: 'Total Outstanding (₹)', visible: true, width: 150 },
      { id: 'risk_level', label: 'Risk Level', visible: true, width: 100 },
      { id: 'credit_limit_paise', label: 'Credit Limit (₹)', visible: true, width: 130 },
    ],
    defaultSortBy: [{ field: 'total_outstanding_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'customer_payment_behavior_report',
    name: 'Customer Payment Behavior Report',
    description: 'Credit collection track record, payment delay days, late payment frequency, and credit reliability',
    dataSource: 'customer_payment_behavior',
    category: 'Credit & A/R Reports',
    availableDimensions: ['customer_code', 'customer_name', 'phone', 'category', 'reliability_rating'],
    availableMeasures: [
      'total_credit_invoices',
      'total_credit_sales_paise',
      'total_collections_paise',
      'current_balance_paise',
      'avg_days_to_pay',
      'late_payments_count',
    ],
    defaultColumns: [
      { id: 'customer_name', label: 'Customer', visible: true, width: 160, pinned: true },
      { id: 'total_credit_invoices', label: 'Credit Invoices', visible: true, width: 120 },
      { id: 'total_credit_sales_paise', label: 'Total Credit (₹)', visible: true, width: 130 },
      { id: 'total_collections_paise', label: 'Total Collections (₹)', visible: true, width: 140 },
      { id: 'current_balance_paise', label: 'Current Balance (₹)', visible: true, width: 140 },
      { id: 'avg_days_to_pay', label: 'Avg Delay (Days)', visible: true, width: 130 },
      { id: 'late_payments_count', label: 'Late Payments', visible: true, width: 120 },
      { id: 'reliability_rating', label: 'Rating', visible: true, width: 100 },
    ],
    defaultSortBy: [{ field: 'total_credit_sales_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'customer_advance_report',
    name: 'Customer Advance & Deposit Report',
    description: 'Customer advance deposits, usage allocations to invoices, and remaining unspent balances',
    dataSource: 'customer_advances',
    category: 'Credit & A/R Reports',
    availableDimensions: [
      'deposit_date',
      'customer_code',
      'customer_name',
      'phone',
      'method',
      'reference_number',
      'status',
      'notes',
    ],
    availableMeasures: [
      'deposit_amount_paise',
      'used_amount_paise',
      'remaining_balance_paise',
      'deposit_count',
    ],
    defaultColumns: [
      { id: 'deposit_date', label: 'Deposit Date', visible: true, width: 110, pinned: true },
      { id: 'customer_name', label: 'Customer', visible: true, width: 160 },
      { id: 'method', label: 'Payment Method', visible: true, width: 130 },
      { id: 'deposit_amount_paise', label: 'Deposit (₹)', visible: true, width: 120 },
      { id: 'used_amount_paise', label: 'Used / Allocated (₹)', visible: true, width: 140 },
      { id: 'remaining_balance_paise', label: 'Remaining Balance (₹)', visible: true, width: 150 },
      { id: 'status', label: 'Status', visible: true, width: 120 },
      { id: 'reference_number', label: 'Ref / Notes', visible: true, width: 150 },
    ],
    defaultSortBy: [{ field: 'deposit_date', direction: 'desc' }],
    pageSize: 50,
  },

  // ============================================================================
  // Section A, B, C — Inventory, Meat Yield & Wastage Reports (Phase 4)
  // ============================================================================

  {
    id: 'stock_on_hand_report',
    name: 'Stock on Hand Report',
    description: 'Current physical inventory snapshot by batch, weight, unit cost, and total valuation',
    dataSource: 'stock_on_hand',
    category: 'Inventory & Yield',
    availableDimensions: [
      'product_name',
      'variant_name',
      'sku',
      'category',
      'batch_number',
      'unit_type',
      'received_date',
      'batch_status',
    ],
    availableMeasures: [
      'stock_quantity',
      'weight_kg',
      'units_count',
      'unit_cost_paise',
      'stock_valuation_paise',
      'batches_count',
    ],
    defaultColumns: [
      { id: 'product_name', label: 'Product', visible: true, width: 160, pinned: true },
      { id: 'variant_name', label: 'Variant', visible: true, width: 140 },
      { id: 'category', label: 'Category', visible: true, width: 110 },
      { id: 'batch_number', label: 'Batch #', visible: true, width: 140 },
      { id: 'stock_quantity', label: 'Quantity', visible: true, width: 100 },
      { id: 'weight_kg', label: 'Weight (kg)', visible: true, width: 110 },
      { id: 'unit_cost_paise', label: 'Unit Cost (₹)', visible: true, width: 120 },
      { id: 'stock_valuation_paise', label: 'Stock Value (₹)', visible: true, width: 130 },
      { id: 'received_date', label: 'Received Date', visible: true, width: 120 },
    ],
    defaultSortBy: [{ field: 'stock_valuation_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'stock_movement_report',
    name: 'Stock Movement Ledger Report',
    description: 'Complete inflow/outflow audit (Purchases, Transfers In/Out, Sales, Returns, Wastage, Adjustments) from inventory_ledger',
    dataSource: 'inventory_movement_ledger',
    category: 'Inventory & Yield',
    availableDimensions: ['product_name', 'variant_name', 'category', 'unit_type'],
    availableMeasures: [
      'purchases_qty',
      'transfers_in_qty',
      'returns_qty',
      'sales_qty',
      'transfers_out_qty',
      'wastage_qty',
      'adjustments_qty',
      'closing_stock_qty',
      'closing_valuation_paise',
    ],
    defaultColumns: [
      { id: 'product_name', label: 'Product', visible: true, width: 160, pinned: true },
      { id: 'variant_name', label: 'Variant', visible: true, width: 130 },
      { id: 'purchases_qty', label: 'Purchases (+)', visible: true, width: 110 },
      { id: 'transfers_in_qty', label: 'Transfers In (+)', visible: true, width: 120 },
      { id: 'returns_qty', label: 'Returns (+)', visible: true, width: 100 },
      { id: 'sales_qty', label: 'Sales (-)', visible: true, width: 100 },
      { id: 'transfers_out_qty', label: 'Transfers Out (-)', visible: true, width: 120 },
      { id: 'wastage_qty', label: 'Wastage (-)', visible: true, width: 105 },
      { id: 'adjustments_qty', label: 'Adjustments (+/-)', visible: true, width: 130 },
      { id: 'closing_stock_qty', label: 'Closing Stock', visible: true, width: 120 },
      { id: 'closing_valuation_paise', label: 'Closing Value (₹)', visible: true, width: 130 },
    ],
    defaultSortBy: [{ field: 'closing_valuation_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'stock_valuation_report',
    name: 'Stock Valuation & COGS Report',
    description: 'Inventory balance valuation matching the Stock Valuation module with WAC, Last Purchase Cost, and Standard Costing',
    dataSource: 'cogs_inventory',
    category: 'Inventory & Yield',
    availableDimensions: ['product_name', 'variant_name', 'sku', 'category', 'unit_type', 'costing_method_label'],
    availableMeasures: [
      'stock_weight_kg',
      'cost_price_paise_per_unit',
      'last_purchase_cost_paise',
      'weighted_average_cost_paise',
      'selling_price_paise',
      'stock_valuation_paise',
    ],
    defaultColumns: [
      { id: 'product_name', label: 'Product', visible: true, width: 160, pinned: true },
      { id: 'variant_name', label: 'Variant', visible: true, width: 140 },
      { id: 'category', label: 'Category', visible: true, width: 110 },
      { id: 'stock_weight_kg', label: 'Stock (kg)', visible: true, width: 100 },
      { id: 'costing_method_label', label: 'Cost Method', visible: true, width: 140 },
      { id: 'weighted_average_cost_paise', label: 'WAC / Cost (₹)', visible: true, width: 130 },
      { id: 'selling_price_paise', label: 'Selling Price (₹)', visible: true, width: 130 },
      { id: 'stock_valuation_paise', label: 'Valuation (₹)', visible: true, width: 140 },
    ],
    defaultSortBy: [{ field: 'stock_valuation_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'meat_yield_report',
    name: 'Meat-Shop Yield & Butchery Processing Report',
    description: 'Deboning and carcass yield analysis comparing Realized Saleable Cuts % vs Expected Yield ratio with variance',
    dataSource: 'meat_yield_processing',
    category: 'Inventory & Yield',
    availableDimensions: ['run_number', 'run_date', 'raw_product_name', 'raw_variant_name', 'processed_by', 'notes'],
    availableMeasures: [
      'input_weight_kg',
      'input_cost_paise',
      'saleable_output_weight_kg',
      'saleable_output_cost_paise',
      'waste_weight_kg',
      'actual_yield_percent',
      'expected_yield_percent',
      'yield_variance_percent',
    ],
    defaultColumns: [
      { id: 'run_number', label: 'Run #', visible: true, width: 130, pinned: true },
      { id: 'run_date', label: 'Date', visible: true, width: 105 },
      { id: 'raw_product_name', label: 'Raw Carcass', visible: true, width: 150 },
      { id: 'input_weight_kg', label: 'Input (kg)', visible: true, width: 110 },
      { id: 'saleable_output_weight_kg', label: 'Saleable Meat (kg)', visible: true, width: 140 },
      { id: 'waste_weight_kg', label: 'Trim / Waste (kg)', visible: true, width: 130 },
      { id: 'actual_yield_percent', label: 'Actual Yield %', visible: true, width: 125 },
      { id: 'expected_yield_percent', label: 'Expected Yield %', visible: true, width: 135 },
      { id: 'yield_variance_percent', label: 'Variance %', visible: true, width: 115 },
      { id: 'processed_by', label: 'Butcher', visible: true, width: 120 },
    ],
    defaultSortBy: [{ field: 'run_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'wastage_loss_report',
    name: 'Wastage, Spoilage & Loss Report',
    description: 'Itemized wastage entries from inventory_ledger tracking weight loss, cost impact, and loss reasons',
    dataSource: 'inventory_wastage_loss',
    category: 'Inventory & Yield',
    availableDimensions: ['wastage_date', 'product_name', 'variant_name', 'category', 'reason', 'logged_by', 'reference_number'],
    availableMeasures: ['wastage_weight_kg', 'wastage_units', 'unit_cost_paise', 'total_loss_paise', 'incident_count'],
    defaultColumns: [
      { id: 'wastage_date', label: 'Date', visible: true, width: 105, pinned: true },
      { id: 'product_name', label: 'Product', visible: true, width: 150 },
      { id: 'variant_name', label: 'Variant', visible: true, width: 130 },
      { id: 'reason', label: 'Loss Reason', visible: true, width: 160 },
      { id: 'wastage_weight_kg', label: 'Weight (kg)', visible: true, width: 110 },
      { id: 'unit_cost_paise', label: 'Unit Cost (₹)', visible: true, width: 120 },
      { id: 'total_loss_paise', label: 'Total Loss (₹)', visible: true, width: 130 },
      { id: 'logged_by', label: 'Logged By', visible: true, width: 120 },
    ],
    defaultSortBy: [{ field: 'total_loss_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'dead_stock_report',
    name: 'Dead Stock & Slow-Moving Products',
    description: 'Identifies unsold inventory sitting beyond threshold days with rule-based promotional recommendations',
    dataSource: 'dead_stock_analysis',
    category: 'Inventory & Yield',
    availableDimensions: ['product_name', 'variant_name', 'category', 'sku', 'last_sale_date', 'recommended_action'],
    availableMeasures: ['current_stock_qty', 'stock_value_paise', 'days_without_sale', 'dead_items_count'],
    defaultColumns: [
      { id: 'product_name', label: 'Product', visible: true, width: 160, pinned: true },
      { id: 'variant_name', label: 'Variant', visible: true, width: 140 },
      { id: 'category', label: 'Category', visible: true, width: 110 },
      { id: 'current_stock_qty', label: 'Current Stock', visible: true, width: 120 },
      { id: 'stock_value_paise', label: 'Stock Value (₹)', visible: true, width: 130 },
      { id: 'last_sale_date', label: 'Last Sale', visible: true, width: 110 },
      { id: 'days_without_sale', label: 'Days Idle', visible: true, width: 100 },
      { id: 'recommended_action', label: 'Recommended Action', visible: true, width: 200 },
    ],
    defaultSortBy: [{ field: 'days_without_sale', direction: 'desc' }],
    pageSize: 50,
  },

  // ============================================================================
  // Section D — Purchase & Supplier Reports (Phase 4)
  // ============================================================================

  {
    id: 'purchase_transactions_report',
    name: 'Purchase Transactions Report',
    description: 'Itemized supplier purchase receipts, shipment weights, and procurement costs',
    dataSource: 'purchase_transactions',
    category: 'Purchases & Suppliers',
    availableDimensions: ['purchase_date', 'supplier_name', 'supplier_code', 'product_name', 'variant_name', 'category', 'logged_by'],
    availableMeasures: ['purchase_quantity', 'purchase_weight_kg', 'purchase_cost_paise', 'unit_cost_paise', 'purchase_count'],
    defaultColumns: [
      { id: 'purchase_date', label: 'Date', visible: true, width: 105, pinned: true },
      { id: 'supplier_name', label: 'Supplier', visible: true, width: 160 },
      { id: 'product_name', label: 'Product', visible: true, width: 150 },
      { id: 'variant_name', label: 'Variant', visible: true, width: 130 },
      { id: 'purchase_weight_kg', label: 'Weight (kg)', visible: true, width: 110 },
      { id: 'unit_cost_paise', label: 'Cost / Unit (₹)', visible: true, width: 130 },
      { id: 'purchase_cost_paise', label: 'Total Cost (₹)', visible: true, width: 130 },
      { id: 'logged_by', label: 'Received By', visible: true, width: 120 },
    ],
    defaultSortBy: [{ field: 'purchase_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'supplier_summary_report',
    name: 'Supplier Procurement & Payables Report',
    description: 'Supplier purchase totals, volume, order frequencies, and outstanding payables matching Supplier Ledger',
    dataSource: 'supplier_procurement_summary',
    category: 'Purchases & Suppliers',
    availableDimensions: ['supplier_code', 'supplier_name', 'contact', 'last_purchase_date'],
    availableMeasures: ['total_purchases_count', 'total_weight_kg', 'total_spend_paise', 'avg_order_cost_paise', 'outstanding_payable_paise', 'supplier_count'],
    defaultColumns: [
      { id: 'supplier_name', label: 'Supplier', visible: true, width: 170, pinned: true },
      { id: 'supplier_code', label: 'Code', visible: true, width: 100 },
      { id: 'total_purchases_count', label: 'Orders Count', visible: true, width: 110 },
      { id: 'total_weight_kg', label: 'Total Weight (kg)', visible: true, width: 130 },
      { id: 'total_spend_paise', label: 'Total Spend (₹)', visible: true, width: 140 },
      { id: 'avg_order_cost_paise', label: 'Avg Order (₹)', visible: true, width: 130 },
      { id: 'last_purchase_date', label: 'Last Purchase', visible: true, width: 120 },
      { id: 'outstanding_payable_paise', label: 'Outstanding Payable (₹)', visible: true, width: 170 },
    ],
    defaultSortBy: [{ field: 'total_spend_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'purchase_price_variance_report',
    name: 'Purchase Price Variance & Margin Impact',
    description: 'Cost changes between consecutive purchases with percentage increase and gross margin erosion warning',
    dataSource: 'purchase_cost_variance',
    category: 'Purchases & Suppliers',
    availableDimensions: ['product_name', 'variant_name', 'category', 'unit_type', 'cost_trend'],
    availableMeasures: [
      'current_purchase_cost_paise',
      'previous_purchase_cost_paise',
      'cost_difference_paise',
      'cost_change_percent',
      'selling_price_paise',
      'margin_after_increase_percent',
    ],
    defaultColumns: [
      { id: 'product_name', label: 'Product', visible: true, width: 160, pinned: true },
      { id: 'variant_name', label: 'Variant', visible: true, width: 140 },
      { id: 'cost_trend', label: 'Trend', visible: true, width: 120 },
      { id: 'previous_purchase_cost_paise', label: 'Base Cost (₹)', visible: true, width: 120 },
      { id: 'current_purchase_cost_paise', label: 'Current Cost (₹)', visible: true, width: 130 },
      { id: 'cost_difference_paise', label: 'Variance (₹)', visible: true, width: 120 },
      { id: 'cost_change_percent', label: 'Cost Change %', visible: true, width: 130 },
      { id: 'selling_price_paise', label: 'Selling Price (₹)', visible: true, width: 130 },
      { id: 'margin_after_increase_percent', label: 'Effective Margin %', visible: true, width: 150 },
    ],
    defaultSortBy: [{ field: 'cost_change_percent', direction: 'desc' }],
    pageSize: 50,
  },

  // ============================================================================
  // Section A, B — Expenses, Cash Box & Shift Reports (Phase 5)
  // ============================================================================

  {
    id: 'expense_records_report',
    name: 'Expense Records & Spending Report',
    description: 'Store operational expenses grouped by category, payment method, and vendors with trend breakdowns',
    dataSource: 'expense_records',
    category: 'Expenses & Shifts',
    availableDimensions: ['expense_id', 'expense_date', 'category_name', 'vendor_name', 'payment_method', 'status', 'notes', 'logged_by'],
    availableMeasures: ['amount_paise', 'gst_paise', 'net_amount_paise', 'expenses_count'],
    defaultColumns: [
      { id: 'expense_date', label: 'Date', visible: true, width: 110, pinned: true },
      { id: 'category_name', label: 'Category', visible: true, width: 140 },
      { id: 'vendor_name', label: 'Vendor / Payee', visible: true, width: 160 },
      { id: 'amount_paise', label: 'Amount (₹)', visible: true, width: 120 },
      { id: 'payment_method', label: 'Method', visible: true, width: 120 },
      { id: 'status', label: 'Status', visible: true, width: 100 },
      { id: 'notes', label: 'Description', visible: true, width: 180 },
      { id: 'logged_by', label: 'Logged By', visible: true, width: 130 },
    ],
    defaultSortBy: [{ field: 'expense_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'cash_box_reconciliation_report',
    name: 'Cash Box & Daily Reconciliation Report',
    description: 'Daily cash register flow: Opening Cash + Sales Inflows + Receipts - Withdrawals - Expenses = Expected vs Actual Counted Cash',
    dataSource: 'cash_box_shifts',
    category: 'Expenses & Shifts',
    availableDimensions: ['session_id', 'shift_date', 'employee_name', 'reconciliation_status', 'variance_reason'],
    availableMeasures: ['opening_cash_paise', 'cash_sales_paise', 'cash_in_paise', 'cash_out_paise', 'expenses_paise', 'expected_cash_paise', 'actual_cash_paise', 'variance_paise', 'shifts_count'],
    defaultColumns: [
      { id: 'shift_date', label: 'Date', visible: true, width: 110, pinned: true },
      { id: 'employee_name', label: 'Cashier', visible: true, width: 140 },
      { id: 'opening_cash_paise', label: 'Opening (₹)', visible: true, width: 120 },
      { id: 'cash_sales_paise', label: 'Cash Sales (₹)', visible: true, width: 130 },
      { id: 'cash_in_paise', label: 'Cash In (₹)', visible: true, width: 110 },
      { id: 'expenses_paise', label: 'Expenses (₹)', visible: true, width: 120 },
      { id: 'cash_out_paise', label: 'Withdrawals (₹)', visible: true, width: 130 },
      { id: 'expected_cash_paise', label: 'Expected (₹)', visible: true, width: 130 },
      { id: 'actual_cash_paise', label: 'Counted (₹)', visible: true, width: 130 },
      { id: 'variance_paise', label: 'Variance (₹)', visible: true, width: 130 },
      { id: 'reconciliation_status', label: 'Status', visible: true, width: 110 },
    ],
    defaultSortBy: [{ field: 'shift_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'shift_closing_report',
    name: 'Shift Summary & Variance Report',
    description: 'Shift register snapshots with sales breakdown by tender (Cash/UPI/Card/Credit), expenses, withdrawals, and declared variance',
    dataSource: 'cash_box_shifts',
    category: 'Expenses & Shifts',
    availableDimensions: ['session_id', 'shift_date', 'employee_name', 'start_time', 'end_time', 'reconciliation_status', 'variance_reason'],
    availableMeasures: ['opening_cash_paise', 'cash_sales_paise', 'upi_sales_paise', 'card_sales_paise', 'credit_sales_paise', 'expenses_paise', 'expected_cash_paise', 'actual_cash_paise', 'variance_paise'],
    defaultColumns: [
      { id: 'session_id', label: 'Shift #', visible: true, width: 90, pinned: true },
      { id: 'employee_name', label: 'Cashier', visible: true, width: 140 },
      { id: 'start_time', label: 'Started', visible: true, width: 140 },
      { id: 'end_time', label: 'Closed', visible: true, width: 140 },
      { id: 'cash_sales_paise', label: 'Cash Sales (₹)', visible: true, width: 120 },
      { id: 'upi_sales_paise', label: 'UPI Sales (₹)', visible: true, width: 120 },
      { id: 'credit_sales_paise', label: 'Credit (₹)', visible: true, width: 110 },
      { id: 'expected_cash_paise', label: 'Expected (₹)', visible: true, width: 120 },
      { id: 'actual_cash_paise', label: 'Actual (₹)', visible: true, width: 120 },
      { id: 'variance_paise', label: 'Variance (₹)', visible: true, width: 120 },
      { id: 'variance_reason', label: 'Reason / Notes', visible: true, width: 160 },
    ],
    defaultSortBy: [{ field: 'session_id', direction: 'desc' }],
    pageSize: 50,
  },

  // ============================================================================
  // Section C, D, E — Employees, Voids & Audit Reports (Phase 5)
  // ============================================================================

  {
    id: 'employee_cashier_report',
    name: 'Employee & Cashier Accountability Report',
    description: 'Factual cashier accountability: Sales volume, invoice counts, average ticket, discounts given, collections, returns, and void counts',
    dataSource: 'employee_cashier_performance',
    category: 'Operations & Audit',
    availableDimensions: ['employee_id', 'cashier_name', 'role'],
    availableMeasures: ['total_sales_paise', 'invoices_count', 'avg_invoice_paise', 'discounts_given_paise', 'cash_collected_paise', 'upi_collected_paise', 'credit_sales_paise', 'returns_count', 'refunds_paise', 'voids_count'],
    defaultColumns: [
      { id: 'cashier_name', label: 'Cashier / Staff', visible: true, width: 160, pinned: true },
      { id: 'role', label: 'Role', visible: true, width: 100 },
      { id: 'invoices_count', label: 'Invoices', visible: true, width: 90 },
      { id: 'total_sales_paise', label: 'Total Sales (₹)', visible: true, width: 130 },
      { id: 'avg_invoice_paise', label: 'Avg Ticket (₹)', visible: true, width: 120 },
      { id: 'cash_collected_paise', label: 'Cash (₹)', visible: true, width: 110 },
      { id: 'upi_collected_paise', label: 'UPI (₹)', visible: true, width: 110 },
      { id: 'discounts_given_paise', label: 'Discounts (₹)', visible: true, width: 120 },
      { id: 'returns_count', label: 'Returns', visible: true, width: 90 },
      { id: 'voids_count', label: 'Voids', visible: true, width: 90 },
    ],
    defaultSortBy: [{ field: 'total_sales_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'void_cancelled_report',
    name: 'Void & Cancelled Transactions Report',
    description: 'Dedicated log of cancelled, voided, and aborted invoices with manager approvals and reasons',
    dataSource: 'void_cancelled_transactions',
    category: 'Operations & Audit',
    availableDimensions: ['invoice_number', 'cancellation_date', 'cancellation_time', 'cashier_name', 'approved_by', 'customer_name', 'cancellation_reason', 'status'],
    availableMeasures: ['void_amount_paise', 'void_count'],
    defaultColumns: [
      { id: 'invoice_number', label: 'Invoice #', visible: true, width: 130, pinned: true },
      { id: 'cancellation_date', label: 'Date', visible: true, width: 105 },
      { id: 'cancellation_time', label: 'Time', visible: true, width: 90 },
      { id: 'cashier_name', label: 'Cashier', visible: true, width: 130 },
      { id: 'customer_name', label: 'Customer', visible: true, width: 140 },
      { id: 'void_amount_paise', label: 'Void Amount (₹)', visible: true, width: 130 },
      { id: 'cancellation_reason', label: 'Reason', visible: true, width: 200 },
      { id: 'approved_by', label: 'Approved By', visible: true, width: 130 },
    ],
    defaultSortBy: [{ field: 'cancellation_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'unified_audit_report',
    name: 'Unified System Audit Trail Report',
    description: 'Centralized audit log tracking Product Tracking Changes, Purchase Reversals, HR Logs, and Administrative Actions',
    dataSource: 'unified_audit_trail',
    category: 'Operations & Audit',
    availableDimensions: ['audit_date', 'audit_time', 'module_entity', 'action_type', 'user_name', 'reason', 'details'],
    availableMeasures: ['audit_events_count'],
    defaultColumns: [
      { id: 'audit_date', label: 'Date', visible: true, width: 105, pinned: true },
      { id: 'audit_time', label: 'Time', visible: true, width: 90 },
      { id: 'module_entity', label: 'Module / Subsystem', visible: true, width: 150 },
      { id: 'action_type', label: 'Action', visible: true, width: 160 },
      { id: 'user_name', label: 'User', visible: true, width: 130 },
      { id: 'reason', label: 'Reason / Notes', visible: true, width: 180 },
      { id: 'details', label: 'Details', visible: true, width: 180 },
    ],
    defaultSortBy: [{ field: 'audit_date', direction: 'desc' }],
    pageSize: 50,
  },

  // ============================================================================
  // Section F, G — Tax / GST & Business Performance Reports (Phase 5)
  // ============================================================================

  {
    id: 'tax_gst_report',
    name: 'Tax / GST Summary & Invoices Report',
    description: 'Itemized GST tax calculations (Taxable Sales, CGST, SGST, IGST, and Exempt sales) based on active product tax settings',
    dataSource: 'tax_gst_breakdown',
    category: 'Tax & Performance',
    availableDimensions: ['invoice_number', 'invoice_date', 'product_name', 'variant_name', 'tax_rate_percent', 'is_exempt'],
    availableMeasures: ['taxable_amount_paise', 'cgst_paise', 'sgst_paise', 'igst_paise', 'total_tax_paise', 'total_invoice_amount_paise', 'items_count'],
    defaultColumns: [
      { id: 'invoice_number', label: 'Invoice #', visible: true, width: 130, pinned: true },
      { id: 'invoice_date', label: 'Date', visible: true, width: 105 },
      { id: 'product_name', label: 'Product', visible: true, width: 150 },
      { id: 'tax_rate_percent', label: 'Rate %', visible: true, width: 85 },
      { id: 'is_exempt', label: 'Treatment', visible: true, width: 100 },
      { id: 'taxable_amount_paise', label: 'Taxable (₹)', visible: true, width: 120 },
      { id: 'cgst_paise', label: 'CGST (₹)', visible: true, width: 105 },
      { id: 'sgst_paise', label: 'SGST (₹)', visible: true, width: 105 },
      { id: 'total_tax_paise', label: 'Total Tax (₹)', visible: true, width: 120 },
      { id: 'total_invoice_amount_paise', label: 'Total (₹)', visible: true, width: 120 },
    ],
    defaultSortBy: [{ field: 'invoice_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'business_performance_report',
    name: 'Business Performance & Executive KPI Report',
    description: 'Master executive business health report (Revenue, COGS, Gross Profit, Expenses, Margins, Net Operating Profit, Average Ticket)',
    dataSource: 'business_performance',
    category: 'Tax & Performance',
    availableDimensions: ['invoice_date', 'month_year', 'day_of_week', 'hour_of_day', 'category'],
    availableMeasures: ['gross_sales_paise', 'discounts_paise', 'net_sales_paise', 'cogs_paise', 'gross_profit_paise', 'gross_margin_percent', 'total_weight_kg', 'total_quantity', 'invoices_count'],
    defaultColumns: [
      { id: 'invoice_date', label: 'Date', visible: true, width: 110, pinned: true },
      { id: 'gross_sales_paise', label: 'Gross Revenue (₹)', visible: true, width: 140 },
      { id: 'discounts_paise', label: 'Discounts (₹)', visible: true, width: 120 },
      { id: 'net_sales_paise', label: 'Net Sales (₹)', visible: true, width: 130 },
      { id: 'cogs_paise', label: 'COGS (₹)', visible: true, width: 120 },
      { id: 'gross_profit_paise', label: 'Gross Profit (₹)', visible: true, width: 130 },
      { id: 'gross_margin_percent', label: 'Margin %', visible: true, width: 105 },
      { id: 'total_weight_kg', label: 'Weight (kg)', visible: true, width: 110 },
      { id: 'invoices_count', label: 'Orders', visible: true, width: 90 },
    ],
    defaultSortBy: [{ field: 'invoice_date', direction: 'desc' }],
    pageSize: 50,
  },

  // ==========================================================================
  // DELIVERY & DISPATCH REPORTS
  // ==========================================================================
  {
    id: 'delivery_transactions_report',
    name: 'Delivery Transactions Report',
    description: 'Master log of all delivery shipments with invoice, customer, address, driver, fee, status, and duration metrics',
    dataSource: 'delivery_operations',
    category: 'Delivery Reports',
    availableDimensions: [
      'delivery_number', 'requested_date', 'time_slot', 'delivery_type', 'priority',
      'status', 'customer_name', 'customer_phone', 'address_area', 'zone_name',
      'driver_name', 'driver_phone', 'vehicle_number', 'invoice_number', 'payment_method', 'payment_status'
    ],
    availableMeasures: [
      'subtotal_paise', 'delivery_charge_paise', 'total_paise', 'cod_expected_paise',
      'cod_collected_paise', 'cod_variance_paise', 'estimated_minutes', 'actual_prep_minutes',
      'actual_delivery_minutes', 'deliveries_count'
    ],
    defaultColumns: [
      { id: 'delivery_number', label: 'Delivery #', visible: true, width: 140, pinned: true },
      { id: 'requested_date', label: 'Date', visible: true, width: 100 },
      { id: 'time_slot', label: 'Slot', visible: true, width: 110 },
      { id: 'status', label: 'Status', visible: true, width: 110 },
      { id: 'customer_name', label: 'Customer', visible: true, width: 140 },
      { id: 'address_area', label: 'Area', visible: true, width: 130 },
      { id: 'zone_name', label: 'Zone', visible: true, width: 120 },
      { id: 'driver_name', label: 'Driver', visible: true, width: 120 },
      { id: 'total_paise', label: 'Total (₹)', visible: true, width: 110 },
      { id: 'delivery_charge_paise', label: 'Delivery Fee (₹)', visible: true, width: 115 },
      { id: 'payment_method', label: 'Payment', visible: true, width: 95 },
      { id: 'actual_delivery_minutes', label: 'Duration (m)', visible: true, width: 100 },
    ],
    defaultSortBy: [{ field: 'requested_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'delivery_performance_report',
    name: 'Delivery Performance & SLA Report',
    description: 'Volume, completion rates, average prep & transit times, on-time SLA %, and failure rates',
    dataSource: 'delivery_operations',
    category: 'Delivery Reports',
    availableDimensions: ['requested_date', 'status', 'zone_name', 'driver_name', 'delivery_type'],
    availableMeasures: ['deliveries_count', 'total_paise', 'delivery_charge_paise', 'estimated_minutes', 'actual_prep_minutes', 'actual_delivery_minutes'],
    defaultColumns: [
      { id: 'requested_date', label: 'Date', visible: true, width: 110, pinned: true },
      { id: 'status', label: 'Status', visible: true, width: 110 },
      { id: 'deliveries_count', label: 'Orders', visible: true, width: 90 },
      { id: 'total_paise', label: 'Revenue (₹)', visible: true, width: 120 },
      { id: 'delivery_charge_paise', label: 'Delivery Fees (₹)', visible: true, width: 125 },
      { id: 'actual_prep_minutes', label: 'Avg Prep (m)', visible: true, width: 105 },
      { id: 'actual_delivery_minutes', label: 'Avg Transit (m)', visible: true, width: 110 },
    ],
    defaultSortBy: [{ field: 'requested_date', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'driver_performance_report',
    name: 'Driver Performance & COD Report',
    description: 'Per-driver delivery counts, on-time transit speed, COD cash collections, and variances',
    dataSource: 'delivery_operations',
    category: 'Delivery Reports',
    availableDimensions: ['driver_name', 'driver_phone', 'vehicle_number', 'requested_date'],
    availableMeasures: ['deliveries_count', 'total_paise', 'cod_expected_paise', 'cod_collected_paise', 'cod_variance_paise', 'actual_delivery_minutes'],
    defaultColumns: [
      { id: 'driver_name', label: 'Driver', visible: true, width: 140, pinned: true },
      { id: 'vehicle_number', label: 'Vehicle', visible: true, width: 120 },
      { id: 'deliveries_count', label: 'Deliveries', visible: true, width: 100 },
      { id: 'total_paise', label: 'Order Value (₹)', visible: true, width: 120 },
      { id: 'cod_expected_paise', label: 'COD Expected (₹)', visible: true, width: 130 },
      { id: 'cod_collected_paise', label: 'COD Collected (₹)', visible: true, width: 130 },
      { id: 'cod_variance_paise', label: 'Variance (₹)', visible: true, width: 110 },
      { id: 'actual_delivery_minutes', label: 'Avg Delivery (m)', visible: true, width: 120 },
    ],
    defaultSortBy: [{ field: 'deliveries_count', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'delivery_profitability_report',
    name: 'Delivery Profitability & Unit Economics',
    description: 'Delivery revenue vs driver payouts and estimated fuel costs to identify profitable zones',
    dataSource: 'delivery_operations',
    category: 'Delivery Reports',
    availableDimensions: ['zone_name', 'requested_date', 'delivery_type'],
    availableMeasures: ['deliveries_count', 'total_paise', 'delivery_charge_paise', 'driver_payout_paise', 'contribution_margin_paise'],
    defaultColumns: [
      { id: 'zone_name', label: 'Delivery Zone', visible: true, width: 160, pinned: true },
      { id: 'deliveries_count', label: 'Deliveries', visible: true, width: 100 },
      { id: 'total_paise', label: 'Food Revenue (₹)', visible: true, width: 130 },
      { id: 'delivery_charge_paise', label: 'Delivery Fees (₹)', visible: true, width: 130 },
      { id: 'driver_payout_paise', label: 'Driver Payout (₹)', visible: true, width: 130 },
      { id: 'contribution_margin_paise', label: 'Net Margin (₹)', visible: true, width: 130 },
    ],
    defaultSortBy: [{ field: 'total_paise', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'delivery_zone_report',
    name: 'Delivery Zone Analysis Report',
    description: 'Volume, revenue, average delivery time, and customer locality penetration per zone',
    dataSource: 'delivery_operations',
    category: 'Delivery Reports',
    availableDimensions: ['zone_name', 'address_area', 'requested_date'],
    availableMeasures: ['deliveries_count', 'total_paise', 'delivery_charge_paise', 'actual_delivery_minutes'],
    defaultColumns: [
      { id: 'zone_name', label: 'Zone', visible: true, width: 150, pinned: true },
      { id: 'address_area', label: 'Locality / Area', visible: true, width: 140 },
      { id: 'deliveries_count', label: 'Orders', visible: true, width: 90 },
      { id: 'total_paise', label: 'Total Sales (₹)', visible: true, width: 130 },
      { id: 'delivery_charge_paise', label: 'Delivery Fees (₹)', visible: true, width: 125 },
      { id: 'actual_delivery_minutes', label: 'Avg Transit (m)', visible: true, width: 115 },
    ],
    defaultSortBy: [{ field: 'deliveries_count', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'delivery_sla_report',
    name: 'SLA & Late Delivery Report',
    description: 'Estimated vs actual delivery timelines and violation list to improve speed and customer satisfaction',
    dataSource: 'delivery_operations',
    category: 'Delivery Reports',
    availableDimensions: ['delivery_number', 'requested_date', 'customer_name', 'driver_name', 'zone_name', 'status'],
    availableMeasures: ['estimated_minutes', 'actual_prep_minutes', 'actual_delivery_minutes', 'total_paise'],
    defaultColumns: [
      { id: 'delivery_number', label: 'Delivery #', visible: true, width: 140, pinned: true },
      { id: 'customer_name', label: 'Customer', visible: true, width: 140 },
      { id: 'driver_name', label: 'Driver', visible: true, width: 120 },
      { id: 'zone_name', label: 'Zone', visible: true, width: 130 },
      { id: 'estimated_minutes', label: 'Target SLA (m)', visible: true, width: 110 },
      { id: 'actual_delivery_minutes', label: 'Actual Time (m)', visible: true, width: 115 },
      { id: 'status', label: 'Status', visible: true, width: 110 },
    ],
    defaultSortBy: [{ field: 'actual_delivery_minutes', direction: 'desc' }],
    pageSize: 50,
  },

  {
    id: 'delivery_exceptions_report',
    name: 'Delivery Exceptions & Discrepancies Report',
    description: 'Failed, cancelled, rescheduled, and COD variance orders for audit and daily management review',
    dataSource: 'delivery_operations',
    category: 'Delivery Reports',
    availableDimensions: ['delivery_number', 'requested_date', 'customer_name', 'driver_name', 'status', 'payment_method'],
    availableMeasures: ['cod_expected_paise', 'cod_collected_paise', 'cod_variance_paise', 'total_paise'],
    defaultColumns: [
      { id: 'delivery_number', label: 'Delivery #', visible: true, width: 140, pinned: true },
      { id: 'requested_date', label: 'Date', visible: true, width: 100 },
      { id: 'status', label: 'Status', visible: true, width: 110 },
      { id: 'customer_name', label: 'Customer', visible: true, width: 140 },
      { id: 'driver_name', label: 'Driver', visible: true, width: 120 },
      { id: 'total_paise', label: 'Order Total (₹)', visible: true, width: 120 },
      { id: 'cod_variance_paise', label: 'COD Variance (₹)', visible: true, width: 125 },
    ],
    defaultSortBy: [{ field: 'requested_date', direction: 'desc' }],
    pageSize: 50,
  },
];

export function getAllReportDefinitions(): ReportDefinition[] {
  return reportDefinitionsRegistry;
}

export function getReportDefinition(reportId: string): ReportDefinition | undefined {
  return reportDefinitionsRegistry.find(r => r.id === reportId);
}
